### ISSUE TITLE
Fails to detect bash in FreeBSD

### ISSUE THREAD

**Issue by pjcdawkins** [stecman/symfony-console-completion#14]
Testing (masochistically) in FreeBSD 10.0, in a bash shell, I get this:

```

  [RuntimeException]                                                                
  Cannot generate hook for unknown shell type 'sh'. Available hooks are: bash, zsh  

_completion [-g|--generate-hook] [-p|--program="..."] [--shell-type[="..."]]
```

**Comment by aik099** [comment]
What is `sh` shell? Is it alias to `bash` on FreeBSD? If so, then maybe we can alias it in shell detection code as well.

**Comment by pjcdawkins** [comment]
No it's not `bash`, although it's similar.
http://www.freebsd.org/cgi/man.cgi?query=sh#end

The problem was that the shell type was detected as `sh` after I believed I had changed to `bash` by simply running the command `bash`. Apparently you have to use `chsh bash` to change the shell in FreeBSD.

**Comment by aik099** [comment]
> No it's not bash, although it's similar.

Similar to the point, that auto-complete routines work the same way (e.g. there is `complete` command)?

**Comment by aik099** [comment]
In fact you can use `--shell-type bash` in your hook generation command to generate Bash hook and see if it works. No need to change default shell.
