### ISSUE TITLE
Integrate with Travis CI

### ISSUE THREAD

**Issue by aik099** [stecman/symfony-console-completion#18]
Please integrate with Travis CI to run tests on every code change.

**Comment by aik099** [comment]
Current Tavis config doesn't run any tests, but just installs packages. Is that desired behavior?

**Comment by stecman** [comment]
PHPUnit is running - [have a look at one of the finished jobs](https://travis-ci.org/stecman/symfony-console-completion/jobs/48469808#L246).

**Comment by aik099** [comment]
That is really strange, because there is no call to `phpunit` command in `.travis.yml` file.
