### ISSUE TITLE
Indicate minimal supported PHP version

### ISSUE THREAD

**Issue by aik099** [stecman/symfony-console-completion#21]
I see, that tests on Travis CI are running on PHP 5.4 and PHP 5.5. There is no indication of minimal required version in the `composer.json` file.

My question is: the PHP 5.3 is supported?

In the `src` folder I haven't found any PHP 5.4 specific code, but in `tests` folder I've found short array syntax usage, that will make tests fail on PHP 5.3.

**Comment by pjcdawkins** [comment]
Composer requires 5.3.3.

If you want to make 5.4 a hard requirement, please bump the major version number to 1 to comply with semver (I'm using this in a project whose documentation indicates the minimum PHP version as 5.3.3)

**Comment by aik099** [comment]
I'm also for keeping PHP 5.3 compatibility.

**Comment by duncan3dc** [comment]
5.3 should be dropped as it's EOL.

Making 5.4 the minimum does not require a major version bump. And even if it did it wouldn't apply in this case as this software is still version 0.* which means breaking changes can happen anywhere on the way to 1.0.0

**Comment by aik099** [comment]
If a specific PHP version isn't supported doesn't mean that it's bad version. It works and if hosting using it is happy, then why we need to upgrade.

Fact that libraries bump their PHP requirement just to force other to install new PHP versions without actual need for a library itself really concerns me.

**Comment by pjcdawkins** [comment]
I just notice there are some interesting new features in the pull requests, so please merge and tag those as stable *before* requiring 5.4, if you really want to

**Comment by pjcdawkins** [comment]
Anyway, short array syntax is a very insignificant feature of 5.4, it's no reason to require it

**Comment by aik099** [comment]
I've recently created new server on Amazon Web Services using their `Amazon Linux AMI` and there is still PHP 5.3 installed by default. The `yum install php` also gives me PHP 5.3. Same goes for any CentOS version.

To install PHP 5.4 or PHP 5.5 there you need to connect alternative YUM repositories and experience package conflicts with already installed packages.

**Comment by stecman** [comment]
> short array syntax is a very insignificant feature of 5.4, it's no reason to require it

This has been my view with other projects too, so I'll make the minimum version 5.3.
