### ISSUE TITLE
Use ReadTheDocs service for documentation

### ISSUE THREAD

**Issue by aik099** [stecman/symfony-console-completion#29]
The https://readthedocs.org/ service allows to host documentation with Sphinx search abilities. I recommend using it instead of writing long README.md.

Examples:
* http://phpunit-mink.readthedocs.org/en/latest/getting-started.html
* http://mink.behat.org/en/latest/

**Comment by stecman** [comment]
I'm not too keen on using ReadTheDocs for this library at the moment, as the readme is fairly straight forward and short(ish). I'll close this for now, but ReadTheDocs will definitely be the first choice if the documentation gets any more complicated.
