### ISSUE TITLE
Don't use "assertArraySubset" in test suite

### ISSUE THREAD

**Issue by aik099** [stecman/symfony-console-completion#35]
Using `assertArraySubset` method in test suite requires bumping up PHPUnit dependency to 4.4. I'd recommend using another method/method combination for asserting that.

**Comment by stecman** [comment]
I've kept the PHPUnit version at ~`4.4` for now, so closing this. I don't see any harm in using a newer version of phpunit, since unit tests can be easily run using the composer installed version:

    $ ./vendor/bin/phpunit
