### ISSUE TITLE
Support completion wrapper for multi-app completion

### ISSUE THREAD

**Issue by aik099** [stecman/symfony-console-completion#44]
Consider such use case:

* developer has several Symfony-based projects present on his machine
* each project has `app` executable PHP script in it's root folder
* projects can be added/removed over time
* when in project folder typing `app TAB` should get project-relevant completions

Currently I have to install completion hooks for each project separately, which isn't very user friendly.

Also I'm forced to use `-p` option because otherwise I get no completion:
```bash
source <($HOME/web/d/in-portal.53x/in-portal _completion --generate-hook -p in-portal)
```

**Comment by stecman** [comment]
Do you know if there's any identifying about a Symfony app other than the script being `./app/console`? I've had a think about this in the past, but haven't actually written anything for it.

**Comment by aik099** [comment]
I have no idea. Right now I'm using universal bash script that would auto-complete for `console` by calling `console list --xml` app in current directly and getting output from it. We can use current directory option somehow too to generate directory agnostic completion script.

**Comment by aik099** [comment]
Right main completion line (at least in Bash hook) looks like this:
```bash
RESULT="$(/home/alex/web/d/in-portal.53x/in-portal _completion)";
```
Then we can use some PHP code here to use actual invoked script name instead of hardcoding `/home/alex/web/d/in-portal.53x/in-portal` used to generate completion hook initially.

Or we actually can support static hook generation once (not at every shell login as now) and then user can place it where he needs. But this is more what #30 needs.

**Comment by aik099** [comment]
Changing above line to this did the trick:

```bash
RESULT=$(${1} _completion);
```
In fact I think we can safely do this in any case because it won't hurt to use actual app to get completion for instead of app, used to generate the hook.

**Comment by aik099** [comment]
PR created.
