### ISSUE TITLE
Set default for "_completion --generate-hook -p" command

### ISSUE THREAD

**Issue by aik099** [stecman/symfony-console-completion#45]
Currently the `-p` option is optional which results in completion hook generation, that would only work when absolute path to an app (for which to receive completions) is specified.

I haven't seen a case, where this is needed. Instead I recommend setting default value for `-p` option to be `basename(script)`. This would simplify hook generation command for these use cases.

**Comment by aik099** [comment]
@stecman , ping.

**Comment by stecman** [comment]
Yeah I think this makes sense. I had initially implemented this using absolute paths, so adding the `-p` option was initially a way to support programs run through aliases in BASH, but it looks like the more common thing with completions is to just specify the program's basename as you're suggesting (looking at the scripts in the bash-completion package anyway).

**Comment by aik099** [comment]
PR created, ready for review.
