### ISSUE TITLE
zsh options description

### ISSUE THREAD

**Issue by funivan** [stecman/symfony-console-completion#63]
Hello. Thanks for great package. 
Is it possible to make completion of options more beautiful.
In some programs I see information about options. For example `ls` command.
![03 45 34](https://cloud.githubusercontent.com/assets/425208/10883219/1c32d7d4-8179-11e5-98d7-2f34cb99b263.png)

p.s. I use `zsh`

**Comment by aik099** [comment]
Looks a bit overwhelming to me, because user who pressed TAB TAB wants to see short list of possible options, not the result of `--help` option usage. Don't you agree?

And this doesn't seem to be behavior, that works in Bash as well.

**Comment by funivan** [comment]
In some cases I agree with you. But when there are a lot of commands in most cases it is useful to see description of option because you do not remember option for old command or other developers are not familiar with other commands.
