### ISSUE TITLE
 Add support for Symfony 6.0

### ISSUE THREAD

**Issue by geega** [stecman/symfony-console-completion#91]
Please provide support Symfony v6.

**Comment by asika32764** [comment]
For those who are finding Symfony6 support, I forked a new version here: https://packagist.org/packages/asika/symfony-console-completion

Ans also a PR: https://github.com/stecman/symfony-console-completion/pull/93

**Comment by stecman** [comment]
Released `v0.12.0` with Symfony 6 support thanks to the PR from @asika32764 👍
