### ISSUE TITLE
Symfony 6.3 release encountering PHP Fatal error:  Declaration of return type in CompletionCommand

### ISSUE THREAD

**Issue by apathak18** [stecman/symfony-console-completion#95]
PHP Fatal error:  Declaration of Stecman\Component\Symfony\Console\BashCompletion\CompletionCommand::mergeApplicationDefinition($mergeArgs = true) must be compatible with Symfony\Component\Console\Command\Command::mergeApplicationDefinition(bool $mergeArgs = true): void in /Users/ankit.pathak/Documents/Projects/FeatureRepo/acquia-cms-starterkit/vendor/stecman/symfony-console-completion/src/CompletionCommand.php on line 54

Fatal error: Declaration of Stecman\Component\Symfony\Console\BashCompletion\CompletionCommand::mergeApplicationDefinition($mergeArgs = true) must be compatible with Symfony\Component\Console\Command\Command::mergeApplicationDefinition(bool $mergeArgs = true): void in /Users/ankit.pathak/Documents/Projects/FeatureRepo/acquia-cms-starterkit/vendor/stecman/symfony-console-completion/src/CompletionCommand.php on line 54

**Comment by stecman** [comment]
Fixed by #94 - thanks @rajeshreeputra.

Released in v0.12.1
